<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Site1.Master" AutoEventWireup="true" CodeBehind="AboutUs.aspx.cs" Inherits="dcompare1.Views.AboutUs" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container mt-5" style="text-align: center; padding: 2.5%; padding-left: 0%; padding-right: 0%; font-family: 'Nexa', sans-serif; color: black;">
        <img src="..Asset/logo/aboutusimg.png" style="width: 100%; margin-bottom: 5%;">
        <div style="width: 80%; margin-left: 10%;">
            <h1 style="font-size: 300%; margin-bottom: 2.5%; font-family: 'Nexa', sans-serif;"><b>Tentang Kami</b></h1>
            <p style="font-size: 22px; text-align: justify; letter-spacing: 0.01px;">Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde labore voluptatum totam, tenetur ipsam aliquid quam. Accusamus beatae et sequi tenetur quos ipsa aspernatur culpa voluptas unde quaerat eligendi, odio asperiores molestiae quidem nesciunt eum molestias quae voluptatibus perferendis, deleniti aliquam dolore a nihil. Odit neque culpa eius voluptate aliquam.</p>

            <p style="font-size: 22px; text-align: justify; letter-spacing: 0.01px;">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quasi optio sint suscipit obcaecati, tenetur dolore repudiandae error exercitationem nisi! Architecto nobis cum aspernatur dolorum id culpa tempora? Quod aliquam et blanditiis recusandae, quia nemo eaque minima est iste qui perferendis quibusdam facilis dolores ullam quaerat. Sequi, fugiat, recusandae accusantium laudantium necessitatibus amet minima odio quaerat nesciunt eveniet tempore, sed temporibus culpa. Beatae, explicabo. Voluptatum doloribus quia a accusamus inventore, expedita nemo maiores animi officia eius autem quibusdam alias. Laboriosam est quod odit error voluptates ex. Fuga, deleniti. Facere nesciunt deserunt ipsa mollitia tenetur sunt. Nam autem impedit provident sit consequatur?</p>
            
            <p style="font-size: 22px; text-align: justify; letter-spacing: 0.01px;">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita quia, iusto impedit amet facilis earum dignissimos perspiciatis suscipit blanditiis necessitatibus quos dicta quisquam! Dolores porro praesentium, eaque a sint incidunt nihil consequatur enim ipsa adipisci soluta animi ducimus. Omnis amet recusandae veniam. Modi, laboriosam quia possimus itaque odio atque. Culpa maiores nostrum expedita aspernatur quaerat iusto rerum illum, numquam fuga recusandae distinctio commodi minima, obcaecati reprehenderit. Maiores officiis praesentium expedita ratione necessitatibus. Culpa rem libero dolorem architecto magnam corrupti illo modi quos placeat sed officiis delectus, qui enim! Nisi debitis officiis dignissimos fugit amet natus explicabo ex? Repellendus quo cum sequi itaque similique, maxime fuga blanditiis quae, provident alias nostrum culpa. Eligendi suscipit, asperiores neque architecto culpa voluptatem sequi quibusdam vel sit laudantium deserunt nobis repudiandae earum sed nesciunt dolorum deleniti debitis quisquam quasi aliquid consectetur at beatae omnis assumenda. Aperiam cumque culpa sunt similique. Totam suscipit iusto beatae dignissimos!</p>
        </div>
    </div>
</asp:Content>
