//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dcompare1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camera
    {
        public int Id { get; set; }
        public Nullable<int> resolution { get; set; }
        public Nullable<int> megapixels { get; set; }
        public Nullable<int> frame_rate { get; set; }
    }
}
