//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dcompare1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int user { get; set; }
        public int rating { get; set; }
        public int device { get; set; }
        public int likes { get; set; }
        public int dislikes { get; set; }
        public string review { get; set; }
    
        public virtual Device Device1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
