//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dcompare1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public int audio { get; set; }
        public int battery { get; set; }
        public int connectivity { get; set; }
        public int dimension { get; set; }
        public int display { get; set; }
        public int graphics { get; set; }
        public int memory { get; set; }
        public int port { get; set; }
        public int processor { get; set; }
        public int security { get; set; }
        public int storage { get; set; }
        public int included { get; set; }
        public Nullable<int> keyboard { get; set; }
    
        public virtual Audio Audio1 { get; set; }
        public virtual Battery Battery1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Connectivity Connectivity1 { get; set; }
        public virtual Dimension Dimension1 { get; set; }
        public virtual Display Display1 { get; set; }
        public virtual Graphic Graphic { get; set; }
        public virtual Included Included1 { get; set; }
        public virtual Port Port1 { get; set; }
        public virtual Processor Processor1 { get; set; }
        public virtual Security Security1 { get; set; }
        public virtual Storage Storage1 { get; set; }
        public virtual ltKeyboard ltKeyboard { get; set; }
    }
}
