//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dcompare1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memory
    {
        public int Id { get; set; }
        public int size { get; set; }
        public string data_rate { get; set; }
        public int channel { get; set; }
        public int slot { get; set; }
        public Nullable<int> max_capacity { get; set; }
    }
}
